import Head from "next/head";
import Script from "next/script";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  
       
      <main className={styles.main}>
        <h1 className={styles.title}> Hunting Coders</h1>

        <p className={styles.description}>
          Hunting Coders is a community of developers who are interested in
          learning more about the world of software development.
        </p>

          <div className="blogs">
            <h1>Populer Blogs</h1>
            <div className="blog">
               <h2>How to learn javascript in 2022 ?</h2>
               <p>javascript is the language to desgin logic for the web.</p>
            </div>
            <div className="blog">
               <h2>How to learn javascript in 2022 ?</h2>
               <p>javascript is the language to desgin logic for the web.</p>
            </div>
            <div className="blog">
               <h2>How to learn javascript in 2022 ?</h2>
               <p>javascript is the language to desgin logic for the web.</p>
            </div>
            <div className="blog">
               <h2>How to learn javascript in 2022 ?</h2>
               <p>javascript is the language to desgin logic for the web.</p>
            </div>
          </div>
      </main>
    </div>
  );
}
