import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>festival - dryfruits and spices</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>hello next js</h1>
      </main>
    </div>
  );
}
